import React from "react";
import { Day1 } from "./days/day1";
import { Day2 } from "./days/day2";

export type TData = {
  date: string | null;
  timeSpent: number | null;
  bountiesEarned: number;
  component: React.ReactNode | null;
};

export const data: TData[] = [
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: 0,
    component: null,
  },
];
