import React from "react";
import { Day1 } from "./days/day1";

export type TData = {
  date: string | null;
  timeSpent: number | null;
  bountiesEarned: number | null;
  component: React.ReactNode | null;
};

export const data: TData[] = [
  {
    date: "2025/11/16",
    timeSpent: 180,
    bountiesEarned: 0,
    component: <Day1 />,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
  {
    date: null,
    timeSpent: null,
    bountiesEarned: null,
    component: null,
  },
];
